entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic_conf.yml

api:
  dashboard: true
  insecure: true

log:
  level: INFO                # Levels: ERROR, WARN, INFO, DEBUG
  filePath: /var/log/traefik/traefik.log  # System log file

accessLog:
  filePath: /var/log/traefik/access.log   # Access log file
  bufferingSize: 100                      # Optional buffer
  addInternals: true                      # Include internal services