---
- name: Install and configure webservers 
  hosts: servers
  become: true
  vars_files:
    - vars/main.yaml

  tasks:
    - name: copy the index file
      template:
        src: files/index.html
        dest: ~/index.html.new