---
- name: Install and configure webservers 
  hosts: servers
  become: true
  vars:
    username: iman
  tasks:
  - name: debug module
    debug:
      var: username

  - name: print custom message with variable
    debug:
      msg: this is my variable value "{{ username }}"

  - name: using the if condition
    debug:
      msg: >
        {% if ansible_hostname == "server1" %}
        hello "server1"
        {% else %}
        hostname is not "server1" 
        {% endif %}

  - name: copy index.js
    template:
      src: files/index.j2
      dest: /var/www/html/index.html
    notify:
      - "restarted nginx webserver"


  handlers:
  - name: restarted nginx webserver
    service: 
      name: nginx
      enabled: yes
      state: restarted

