- name: with_item
  hosts: all
  become: yes

  tasks:
    - name: Ensure user is present
      debug:
        msg: >
          {{ item }}
      with_items:
        - test
        - docker
        - kubernetes