- name: with_dict
  hosts: all
  become: yes

  tasks:
    - name: show vars
      debug:
        msg: " {{ item.key }}  {{ item.value.comment }} {{ item.value.uid }}"
      with_dict:
        iman:
          comment: "this is iman comment"
          uid: 1540
        sa:
          comment: "this is sa comment"
          uid: 1541
        ho:
          comment: "this is ho comment"
          uid: 1542
