---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes

  - name: Install nginx
    apt:
      name: nginx
      state: latest
    
  - name: Install net-tools
    apt:
      name: net-tools
      state: latest

