---
- name: Install and configure webservers 
  hosts: servers
  become: true
  vars_files:
    - vars/main.yaml
  # vars:
  #   packages:
  #     - nginx
  #     - net-tools
  tasks:

  - name: update repository
    apt: 
      update_cache: yes

  - name: Install nginx webserver
    apt:
      name: "{{ packages }}"
      state: latest
    # vars:
    #   packages:
    #   - nginx
    #   - net-tools