---

- hosts: servers
  become: true
  tasks:

  - name: update repository index
    apt: 
      update_cache: yes

  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
    
  - name: Install net-tools
    apt:
      name: net-tools
      state: present
