---
- name: Install and configure webservers 
  hosts: servers
  become: true
  vars_prompt:
    - name: process_name
    - name: signal
  tasks:
  - name: find pid
    shell: ps -aux | grep "{{ process_name }}" | grep -v grep| tr -s ' ' | cut -d' ' -f2
    # shell: ps -aux | grep prome | grep -v grep | awk '{print $2}'
    register: pid
    ignore_errors: True
  
  - name: list pid
    debug:
      var: pid.stdout_lines

  - name: kill pid
    shell: kill -"{{ signal }}" "{{ pid.stdout_lines.0 }}"






